### ISSUE TITLE
Why is this not part of turf.js

### ISSUE THREAD

**Issue by moklick** [Turfjs/turf-cut#1]
Why is this not part of turf.js?

**Comment by tcql** [comment]
@moklick we've got a number of pending modules / fixes that we'll be rolling into a release in the future, we just haven't had a chance to wrap everything up yet

**Comment by moklick** [comment]
Ah ok. I didn't know that. Thanks for the fast reply!

**Comment by isaac-jordan** [comment]
@tcql Any idea when this feature will be added in? Do you have any suggestions on how to implement this using things already in turf.js?

**Comment by moklick** [comment]
I also used this module a few month ago. You can just take the turf-cut/index.js file and import it to your existing project.
